# Setup
title:               Ziem
tagline:             'My personal blog'
description:         "Hello! I'm Ziem and this is my personal blog."
url:                 https://ziem.github.io
baseurl:             ''
paginate:            5
paginate_path:       /page/:num/
permalink:           /:title
timezone:            Europe/Warsaw

# About/contact
author:
  name:              Ziem

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom vars
google_analytics_id: UA-203690810-1
